# Generated by Django 4.1.4 on 2023-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_social_github_profile_social_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
