# Generated by Django 4.1.4 on 2023-01-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_project_owner_project_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
