# Generated by Django 4.1.4 on 2023-01-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_project_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
