# Generated by Django 4.1.4 on 2023-01-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_project_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
