# Generated by Django 4.1.4 on 2023-01-07 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_messageroom_message_messageroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to='users.profile'),
        ),
        migrations.AddField(
            model_name='messageroom',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2', to='users.profile'),
        ),
    ]
