# Generated by Django 4.1.4 on 2023-01-07 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_messageroom_user1_messageroom_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageroom',
            old_name='user1',
            new_name='recepient',
        ),
        migrations.RenameField(
            model_name='messageroom',
            old_name='user2',
            new_name='sender',
        ),
    ]
