# Generated by Django 4.1.4 on 2023-01-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_user1_messageroom_recepient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageroom',
            old_name='sender',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='messageroom',
            old_name='recepient',
            new_name='user2',
        ),
    ]
