# Generated by Django 4.1.5 on 2023-01-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_project_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=200),
        ),
    ]
