# Generated by Django 4.1.5 on 2023-01-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_applyteacherrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyteacherrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
