# Generated by Django 4.1.5 on 2023-02-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='value',
            new_name='valuee',
        ),
    ]
