# Generated by Django 4.1.5 on 2023-02-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rename_value_review_valuee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='valuee',
            new_name='value',
        ),
    ]
