# Generated by Django 4.1.7 on 2023-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_project_body_alter_project_demo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meeting_date',
            field=models.CharField(blank=True, default='Meeting Time', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='meeting_link',
            field=models.CharField(blank=True, default='Meeting Link', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.CharField(blank=True, default='Source Link', max_length=2000, null=True),
        ),
    ]
