# Generated by Django 4.1.7 on 2023-03-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_project_meeting_date_alter_project_meeting_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='meeting_date',
            new_name='meeting_time',
        ),
    ]
