# Generated by Django 4.1.7 on 2023-03-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_profile_role_teacher_profile_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=200),
        ),
    ]
