# Generated by Django 4.1.7 on 2023-03-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyteacherrequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='applyteacherrequest',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applyteacherrequest',
            name='school',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
