# Generated by Django 4.1.7 on 2023-03-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_applyteacherrequest_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='teacher',
            new_name='teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.profile'),
        ),
    ]
