# Generated by Django 4.1.7 on 2023-03-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_rename_teacher_profile_teachers_teacher_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images/profiles/'),
        ),
    ]
