# Generated by Django 4.1.7 on 2023-03-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
