# Generated by Django 4.1.7 on 2023-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='static/images/profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, default='Объяснение', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='documents_link',
            field=models.TextField(blank=True, default='Ссылка на гугл докс', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='meeting_link',
            field=models.CharField(blank=True, default='Ссылка на встречу', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='meeting_time',
            field=models.CharField(blank=True, default='Время встречи', max_length=500, null=True),
        ),
    ]
