# Generated by Django 4.1.7 on 2023-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_profile_profile_image_alter_project_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images/profiles/'),
        ),
    ]
